apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: oplog-api
spec:
  build:
     useBuildKit: true
  environments:
    - name: prod
    - name: dev
      build:
        from: main
  components:
    - name: api
      src: ./src
      ports:
        - name: http
          port: 5000
      publicPort: http
      secrets:
        - AzureAd__ClientSecret
        - AzureAd__ClientId
        - KeyVaultEndpoint
      environmentConfig:
        - environment: dev
          identity: 
            azure:
              clientId: d1aa9948-2222-4c9a-b9f4-93e959affe64
          runAsNonRoot: true
          variables:
            ASPNETCORE_URLS: "http://*:5000"
            AllowCorsDomains: "http://localhost:3000, https://frontend-oplog-web-dev.radix.equinor.com"
          replicas: 1
          monitoring: false
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              cpu: "200m"
        - environment: prod
          identity: 
            azure:
              clientId: 6c4f0111-af1b-4222-85ef-1ade127fbecf
          runAsNonRoot: true
          variables:
            ASPNETCORE_URLS: "http://*:5000"
            AllowCorsDomains: "http://localhost:3000, https://frontend-oplog-web-prod.radix.equinor.com, https://oplog.equinor.com"
          horizontalScaling:
            resources:
                memory:
                  averageUtilization: 75
                cpu:
                  averageUtilization: 85
            minReplicas: 1
            maxReplicas: 4
          monitoring: false
          resources:
            requests:
              memory: "512Mi"
              cpu: "100m"
            limits:
              cpu: "200m"
