name: API
on:
  repository_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.0.x"

      - name: Restore
        run: dotnet restore ./src/Oplog.sln

      - name: Build
        run: dotnet build ./src/Oplog.sln --configuration Release --no-restore

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test
        env:
          ConnectionString: ${{ secrets.CI_SQL_CONNECTION_STRING }}
        run: dotnet test ./src/Oplog.IntegrationTests --no-restore --verbosity normal
