name: API
on:
  repository_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:   
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.0.x"

      - name: Nuget
        working-directory: src/Oplog.IntegrationTests
        run: dotnet restore

      - name: Build
        working-directory: src/Oplog.IntegrationTests
        run: dotnet build --configuration Release --no-restore

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:      
      - name: Test
        working-directory: src/Oplog.IntegrationTests
        env:
          ConnectionString: ${{ secrets.CI_SQL_CONNECTION_STRING }}
        run: dotnet test --no-restore --verbosity normal       
  
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      # Docker login
      - uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_URL }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # Builds the Chemcom API
      - name: docker build
        run: |
          docker build src -t ${{ secrets.ACR_URL }}/oplog-api:latest
          docker push ${{ secrets.ACR_URL }}/oplog-api:latest
