name: API
on:
  repository_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore
        run: dotnet restore ./src/Oplog.sln

      - name: Build
        run: dotnet build ./src/Oplog.sln --configuration Release --no-restore

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Start Docker container
        run: |
          docker run -d --name test-container mcr.microsoft.com/mssql/server:2022-latest
          docker ps -a

      # - name: Test
      #   run: dotnet test ./src/Oplog.IntegrationTests --logger "console;verbosity=detailed" --blame-hang-timeout 300s

      - name: Run Tests and Capture Logs
        run: |
           dotnet test ./src/Oplog.IntegrationTests \
             --logger "console;verbosity=detailed" \
             --logger "trx;LogFileName=TestResults.trx" | tee test-output.log
        continue-on-error: true

      - name: Upload Test Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
           name: TestLogs
           path: |
            ./src/Oplog.IntegrationTests/TestResults/TestResults.trx
            test-output.log


      - name: Get Docker container logs
        run: docker logs test-container

      - name: Cleanup Docker containers
        run: docker rm -f $(docker ps -a -q)
        