# This is a basic workflow to help you get started with Actions

name: CI - Integration tests

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.0.x"
      - name: Nuget
        working-directory: src/Oplog.IntegrationTests
        run: dotnet restore
      - name: Build
        working-directory: src/Oplog.IntegrationTests
        run: dotnet build --configuration Release --no-restore
        # runs the tests
      - name: Test
        working-directory: src/Oplog.IntegrationTests
        env:
          ConnectionString: ${{ secrets.CI_SQL_CONNECTION_STRING }}
        run: dotnet test --no-restore --verbosity normal
